#!/bin/bash
# setup.sh — One-shot setup for Pi Monitor
#
# Creates venv, builds frontend, installs system binaries, writes sudoers,
# creates the systemd service, initializes the DB, and starts everything.
#
# Usage:
#   sudo ./setup.sh <username>
#
# All paths are read from backend/.env so you can override them there.
# Configurable env vars (with their defaults):
#   FAN_CONTROL_BIN   /usr/local/bin/pi-monitor-fan-control
#   GOV_CONTROL_BIN   /usr/local/bin/pi-monitor-gov-control
#   PROJECT_DIR       ~<username>/pi-monitor (auto-derived if unset)

set -e

# ---------------------------------------------------------------------------
# Validate invocation
# ---------------------------------------------------------------------------
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Run this script with sudo" >&2
    exit 1
fi

USERNAME="${1:-}"
if [ -z "$USERNAME" ]; then
    echo "Usage: $0 <username>" >&2
    exit 1
fi

USERHOME=$(eval echo ~"$USERNAME")
if [ ! -d "$USERHOME" ]; then
    echo "ERROR: User '$USERNAME' not found or has no home directory" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Load .env — pick up FAN_CONTROL_BIN, GOV_CONTROL_BIN, PROJECT_DIR, PORT, etc.
# ---------------------------------------------------------------------------
ENV_FILE="${USERHOME}/pi-monitor/backend/.env"
if [ -f "$ENV_FILE" ]; then
    # Export only lines that look like KEY=VALUE (skip comments and blanks)
    set -a
    # shellcheck disable=SC1090
    source <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE")
    set +a
else
    echo "ERROR: .env not found at $ENV_FILE" >&2
    echo "       Copy backend/.env.example to backend/.env and fill in your values" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Resolve paths (env overrides take priority, defaults derived from username)
# ---------------------------------------------------------------------------
PROJECT_DIR="${PROJECT_DIR:-$USERHOME/pi-monitor}"
BACKEND_DIR="$PROJECT_DIR/backend"
FRONTEND_DIR="$PROJECT_DIR/frontend"
FAN_CONTROL_BIN="${FAN_CONTROL_BIN:-/usr/local/bin/pi-monitor-fan-control}"
GOV_CONTROL_BIN="${GOV_CONTROL_BIN:-/usr/local/bin/pi-monitor-gov-control}"
PORT="${PORT:-8001}"
SERVICE_NAME="pi-monitor-${USERNAME}"

if [ ! -d "$PROJECT_DIR" ]; then
    echo "ERROR: $PROJECT_DIR not found" >&2
    echo "       Clone the repo first: git clone <url> $PROJECT_DIR" >&2
    exit 1
fi

echo "=========================================="
echo "Pi Monitor Setup"
echo "=========================================="
echo "User        : $USERNAME"
echo "Project dir : $PROJECT_DIR"
echo "Fan control : $FAN_CONTROL_BIN"
echo "Gov control : $GOV_CONTROL_BIN"
echo "Port        : $PORT"
echo "Service     : $SERVICE_NAME"
echo ""

cd "$PROJECT_DIR"

# ========================================
# 1. Frontend build
# ========================================
echo "[1/6] Building frontend..."
su - "$USERNAME" -c "
    # Source nvm if installed (common on Pi / user installs)
    [ -s \"\$HOME/.nvm/nvm.sh\" ] && . \"\$HOME/.nvm/nvm.sh\"
    cd '$FRONTEND_DIR' && npm ci && npm run build
"
echo "[ok] Frontend built"

# ========================================
# 2. Python venv + dependencies
# ========================================
echo "[2/6] Setting up Python backend..."

if [ ! -d "$BACKEND_DIR/venv" ]; then
    python3 -m venv "$BACKEND_DIR/venv"
    echo "      Created virtualenv"
fi

"$BACKEND_DIR/venv/bin/pip" install --upgrade pip > /dev/null 2>&1
"$BACKEND_DIR/venv/bin/pip" install -r "$BACKEND_DIR/requirements.txt" > /dev/null 2>&1
echo "[ok] Backend dependencies installed"

# ========================================
# 3. System binaries
# ========================================
echo "[3/6] Installing system binaries..."
install -m 0755 "$BACKEND_DIR/scripts/fan-control.sh" "$FAN_CONTROL_BIN"
install -m 0755 "$BACKEND_DIR/scripts/gov-control.sh" "$GOV_CONTROL_BIN"
echo "[ok] $FAN_CONTROL_BIN"
echo "[ok] $GOV_CONTROL_BIN"

# ========================================
# 4. Sudoers
# ========================================
echo "[4/6] Writing sudoers..."
SUDOERS_FILE="/etc/sudoers.d/${SERVICE_NAME}"
cat > "$SUDOERS_FILE" << EOF
# Pi Monitor — generated by setup.sh for $USERNAME
$USERNAME ALL=(root) NOPASSWD: $GOV_CONTROL_BIN
$USERNAME ALL=(root) NOPASSWD: $FAN_CONTROL_BIN
$USERNAME ALL=(root) NOPASSWD: /usr/sbin/reboot
EOF
chmod 0440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" > /dev/null 2>&1 || {
    echo "ERROR: sudoers syntax check failed" >&2
    rm -f "$SUDOERS_FILE"
    exit 1
}
echo "[ok] $SUDOERS_FILE"

# ========================================
# 5. Systemd service
# ========================================
echo "[5/6] Installing systemd service..."
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Pi Monitor Backend ($USERNAME)
After=network.target

[Service]
Type=simple
User=$USERNAME
WorkingDirectory=$BACKEND_DIR
EnvironmentFile=$BACKEND_DIR/.env
ExecStart=$BACKEND_DIR/venv/bin/python app.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable  "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
echo "[ok] $SERVICE_FILE (enabled + started)"

# ========================================
# 6. Database init
# ========================================
echo "[6/6] Initializing database..."
cd "$BACKEND_DIR"
sudo -u "$USERNAME" "$BACKEND_DIR/venv/bin/python" - << 'PY'
import os
from dotenv import load_dotenv
load_dotenv()
from database import init_db
init_db()
PY
echo "[ok] Database ready"

# ========================================
# Done
# ========================================
echo ""
echo "=========================================="
echo "Setup complete!"
echo "=========================================="
systemctl status "$SERVICE_NAME" --no-pager -l
echo ""
echo "Useful commands:"
echo "  sudo systemctl restart $SERVICE_NAME"
echo "  sudo journalctl -u $SERVICE_NAME -f"
echo "  http://localhost:${PORT}  (or your tunnel URL)"
echo ""
